[build]
  command = "npm run build"
  publish = "dist"

# Handle SPA routing for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Explicitly redirect login page to the main page with login parameter
[[redirects]]
  from = "/login"
  to = "/?login=true"
  status = 301

# Explicitly redirect register page to the main page with register parameter
[[redirects]]
  from = "/register"
  to = "/?register=true"
  status = 301 