import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "english" | "german" | "spanish" | "french";

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

// Simple translation dictionary
const translations: Record<Language, Record<string, string>> = {
  english: {
    welcomeTitle: "Welcome to Sekcion",
    welcomeSubtitle: "Sekcion is the content workspace to share valuable posts everyday.",
    welcomeDescription: "Receive tailored, algorithm-optimized Twitter posts in <5 minutes.",
    getStarted: "Get started",
    back: "Back",
    continue: "Continue",
    choosePlan: "How would you like to use Sekcion?",
    setupWorkspace: "We'll setup your workspace accordingly.",
    forTeam: "For my team",
    forPersonal: "For personal use",
    teamDescription: "One place to create, review and track content for your team.",
    personalDescription: "Create content for a single Twitter profile.",
    chooseStyle: "Choose your style",
    styleDescription: "You can change the UI style at any time in the settings.",
    light: "Light",
    dark: "Dark",
    chooseLanguage: "Choose the language of your content",
    languageDescription: "Sekcion is in English but you can answer all questions in your chosen language at all times.",
    english: "English",
    german: "German",
    spanish: "Spanish",
    french: "French",
    englishDescription: "Recommended for most users to reach larger audience.",
    germanDescription: "Recommended if your main audience is German.",
    spanishDescription: "Recommended if your main audience is Spanish-speaking.",
    frenchDescription: "Recommended if your main audience is French-speaking.",
    formatTitle: "Pick your preferred post formatting style",
    formatDescription: "Sekcion is trained on millions of viral posts. When you create posts, the best performing posts about the same topics will be used as a reference.",
    postLength: "Post length",
    superLong: "Super long",
    learnPreferences: "Sekcion will learn your individual preferences over time.",
    frequencyTitle: "How often do you want to post per week?",
    frequencyDescription: "We recommend posting at least 1-2 times per week.",
    postingSchedule: "Posting Schedule",
    optimalTime: "Optimal posting time",
    aiSuggest: "AI will suggest",
    onePostWeek: "One post per week",
    postsPerWeek: "posts per week",
    teamInviteTitle: "Invite members to",
    teamInviteDescription: "Team members can collaborate on content creation and share analytics.",
    addTeamMembers: "Invite team members",
    placeholderEmail: "colleague@example.com",
    add: "Add",
    teamMembers: "Team members",
    noMembers: "No team members added yet",
    admin: "Admin",
    member: "Member",
    canInviteLater: "You can invite more members after setup is complete",
    // Dashboard translations
    create: "Create",
    schedule: "Schedule",
    analytics: "Analytics",
    myTweets: "My Tweets",
    createNewTweet: "Create New Tweet",
    recordVoice: "Record Voice",
    uploadMedia: "Upload Media",
    writeText: "Write Text",
    whatsHappening: "What's happening?",
    characters: "characters",
    generateWithAI: "Generate with AI",
    postTweet: "Post Tweet",
    preview: "Preview",
    previewDescription: "See how your tweet will appear",
    upcomingTweets: "Upcoming Tweets",
    scheduledPublication: "Scheduled for publication",
    viewCalendar: "View Calendar",
    aiSuggestions: "AI Suggestions",
    trendingTopics: "Trending topics to write about",
    contentCalendar: "Content Calendar",
    manageSchedule: "Manage and schedule your upcoming tweets",
    impressions: "Impressions",
    totalViews: "Total views of your tweets",
    engagementRate: "Engagement Rate",
    interactions: "Interactions with your content",
    followersGrowth: "Followers Growth",
    newFollowers: "New followers over time",
    profile: "Profile",
    settings: "Settings",
    connectTwitter: "Connect Twitter",
    logout: "Logout",
    // Registration page
    createAccount: "Create your Sekcion account",
    personalizeExperience: "Let's get to know you better to personalize your experience",
    firstName: "First Name",
    lastName: "Last Name",
    usernamePreview: "Username Preview",
    profileAppear: "This is how your profile will appear",
    skipToDashboard: "Skip to dashboard"
  },
  german: {
    welcomeTitle: "Willkommen bei Sekcion",
    welcomeSubtitle: "Sekcion ist der Content-Workspace, um täglich wertvolle Beiträge zu teilen.",
    welcomeDescription: "Erhalten Sie maßgeschneiderte, algorithmusoptimierte Twitter-Beiträge in <5 Minuten.",
    getStarted: "Loslegen",
    back: "Zurück",
    continue: "Weiter",
    choosePlan: "Wie möchten Sie Sekcion nutzen?",
    setupWorkspace: "Wir richten Ihren Arbeitsbereich entsprechend ein.",
    forTeam: "Für mein Team",
    forPersonal: "Für persönliche Nutzung",
    teamDescription: "Ein Ort zum Erstellen, Überprüfen und Verfolgen von Inhalten für Ihr Team.",
    personalDescription: "Erstellen Sie Inhalte für ein einzelnes Twitter-Profil.",
    chooseStyle: "Wählen Sie Ihren Stil",
    styleDescription: "Sie können den UI-Stil jederzeit in den Einstellungen ändern.",
    light: "Hell",
    dark: "Dunkel",
    chooseLanguage: "Wählen Sie die Sprache Ihrer Inhalte",
    languageDescription: "Sekcion ist auf Englisch, aber Sie können alle Fragen jederzeit in Ihrer gewählten Sprache beantworten.",
    english: "Englisch",
    german: "Deutsch",
    spanish: "Spanisch",
    french: "Französisch",
    englishDescription: "Empfohlen für die meisten Benutzer, um ein größeres Publikum zu erreichen.",
    germanDescription: "Empfohlen, wenn Ihre Hauptzielgruppe deutsch ist.",
    spanishDescription: "Empfohlen, wenn Ihre Hauptzielgruppe spanischsprachig ist.",
    frenchDescription: "Empfohlen, wenn Ihre Hauptzielgruppe französischsprachig ist.",
    formatTitle: "Wählen Sie Ihren bevorzugten Beitragsformatierungsstil",
    formatDescription: "Sekcion wird mit Millionen viraler Beiträge trainiert. Wenn Sie Beiträge erstellen, werden die besten Beiträge zu ähnlichen Themen als Referenz verwendet.",
    postLength: "Beitragslänge",
    superLong: "Sehr lang",
    learnPreferences: "Sekcion lernt mit der Zeit Ihre individuellen Präferenzen.",
    frequencyTitle: "Wie oft möchten Sie pro Woche posten?",
    frequencyDescription: "Wir empfehlen, mindestens 1-2 Mal pro Woche zu posten.",
    postingSchedule: "Posting-Zeitplan",
    optimalTime: "Optimale Posting-Zeit",
    aiSuggest: "KI wird vorschlagen",
    onePostWeek: "Ein Beitrag pro Woche",
    postsPerWeek: "Beiträge pro Woche",
    teamInviteTitle: "Laden Sie Mitglieder ein zu",
    teamInviteDescription: "Teammitglieder können bei der Erstellung von Inhalten zusammenarbeiten und Analysen teilen.",
    addTeamMembers: "Teammitglieder einladen",
    placeholderEmail: "kollege@beispiel.de",
    add: "Hinzufügen",
    teamMembers: "Teammitglieder",
    noMembers: "Noch keine Teammitglieder hinzugefügt",
    admin: "Administrator",
    member: "Mitglied",
    canInviteLater: "Sie können nach Abschluss der Einrichtung weitere Mitglieder einladen",
    // Dashboard translations
    create: "Erstellen",
    schedule: "Zeitplan",
    analytics: "Analytik",
    myTweets: "Meine Tweets",
    createNewTweet: "Neuen Tweet erstellen",
    recordVoice: "Sprachaufnahme",
    uploadMedia: "Medien hochladen",
    writeText: "Text schreiben",
    whatsHappening: "Was passiert gerade?",
    characters: "Zeichen",
    generateWithAI: "Mit KI generieren",
    postTweet: "Tweet veröffentlichen",
    preview: "Vorschau",
    previewDescription: "Sehen Sie, wie Ihr Tweet aussehen wird",
    upcomingTweets: "Kommende Tweets",
    scheduledPublication: "Zur Veröffentlichung geplant",
    viewCalendar: "Kalender anzeigen",
    aiSuggestions: "KI-Vorschläge",
    trendingTopics: "Trendthemen zum Schreiben",
    contentCalendar: "Inhaltskalender",
    manageSchedule: "Verwalten und planen Sie Ihre kommenden Tweets",
    impressions: "Impressionen",
    totalViews: "Gesamtansichten Ihrer Tweets",
    engagementRate: "Engagement-Rate",
    interactions: "Interaktionen mit Ihren Inhalten",
    followersGrowth: "Follower-Wachstum",
    newFollowers: "Neue Follower im Laufe der Zeit",
    profile: "Profil",
    settings: "Einstellungen",
    connectTwitter: "Twitter verbinden",
    logout: "Abmelden",
    // Registration page
    createAccount: "Erstellen Sie Ihr Sekcion-Konto",
    personalizeExperience: "Lernen wir Sie besser kennen, um Ihr Erlebnis zu personalisieren",
    firstName: "Vorname",
    lastName: "Nachname",
    usernamePreview: "Benutzername-Vorschau",
    profileAppear: "So wird Ihr Profil erscheinen",
    skipToDashboard: "Zum Dashboard springen"
  },
  spanish: {
    welcomeTitle: "Bienvenido a Sekcion",
    welcomeSubtitle: "Sekcion es el espacio de trabajo de contenido para compartir publicaciones valiosas todos los días.",
    welcomeDescription: "Reciba publicaciones de Twitter optimizadas por algoritmos y personalizadas en <5 minutos.",
    getStarted: "Comenzar",
    back: "Atrás",
    continue: "Continuar",
    choosePlan: "¿Cómo le gustaría usar Sekcion?",
    setupWorkspace: "Configuraremos su espacio de trabajo en consecuencia.",
    forTeam: "Para mi equipo",
    forPersonal: "Para uso personal",
    teamDescription: "Un lugar para crear, revisar y seguir contenido para su equipo.",
    personalDescription: "Cree contenido para un solo perfil de Twitter.",
    chooseStyle: "Elija su estilo",
    styleDescription: "Puede cambiar el estilo de la interfaz en cualquier momento en la configuración.",
    light: "Claro",
    dark: "Oscuro",
    chooseLanguage: "Elija el idioma de su contenido",
    languageDescription: "Sekcion está en inglés, pero puede responder a todas las preguntas en su idioma elegido en todo momento.",
    english: "Inglés",
    german: "Alemán",
    spanish: "Español",
    french: "Francés",
    englishDescription: "Recomendado para la mayoría de los usuarios para llegar a una audiencia más amplia.",
    germanDescription: "Recomendado si su audiencia principal es alemana.",
    spanishDescription: "Recomendado si su audiencia principal habla español.",
    frenchDescription: "Recomendado si su audiencia principal habla francés.",
    formatTitle: "Elija su estilo de formato de publicación preferido",
    formatDescription: "Sekcion está entrenado con millones de publicaciones virales. Cuando crea publicaciones, las mejores publicaciones sobre los mismos temas se utilizarán como referencia.",
    postLength: "Longitud de publicación",
    superLong: "Super larga",
    learnPreferences: "Sekcion aprenderá sus preferencias individuales con el tiempo.",
    frequencyTitle: "¿Con qué frecuencia quiere publicar por semana?",
    frequencyDescription: "Recomendamos publicar al menos 1-2 veces por semana.",
    postingSchedule: "Calendario de publicación",
    optimalTime: "Hora óptima de publicación",
    aiSuggest: "La IA sugerirá",
    onePostWeek: "Una publicación por semana",
    postsPerWeek: "publicaciones por semana",
    teamInviteTitle: "Invitar miembros a",
    teamInviteDescription: "Los miembros del equipo pueden colaborar en la creación de contenido y compartir análisis.",
    addTeamMembers: "Invitar miembros del equipo",
    placeholderEmail: "colega@ejemplo.com",
    add: "Agregar",
    teamMembers: "Miembros del equipo",
    noMembers: "Aún no se han agregado miembros del equipo",
    admin: "Administrador",
    member: "Miembro",
    canInviteLater: "Puede invitar a más miembros después de completar la configuración",
    // Dashboard translations
    create: "Crear",
    schedule: "Programar",
    analytics: "Analítica",
    myTweets: "Mis Tweets",
    createNewTweet: "Crear nuevo Tweet",
    recordVoice: "Grabar voz",
    uploadMedia: "Subir medios",
    writeText: "Escribir texto",
    whatsHappening: "¿Qué está pasando?",
    characters: "caracteres",
    generateWithAI: "Generar con IA",
    postTweet: "Publicar Tweet",
    preview: "Vista previa",
    previewDescription: "Vea cómo aparecerá su tweet",
    upcomingTweets: "Próximos Tweets",
    scheduledPublication: "Programados para publicación",
    viewCalendar: "Ver calendario",
    aiSuggestions: "Sugerencias de IA",
    trendingTopics: "Temas tendencia para escribir",
    contentCalendar: "Calendario de contenido",
    manageSchedule: "Gestione y programe sus próximos tweets",
    impressions: "Impresiones",
    totalViews: "Vistas totales de sus tweets",
    engagementRate: "Tasa de participación",
    interactions: "Interacciones con su contenido",
    followersGrowth: "Crecimiento de seguidores",
    newFollowers: "Nuevos seguidores a lo largo del tiempo",
    profile: "Perfil",
    settings: "Configuración",
    connectTwitter: "Conectar Twitter",
    logout: "Cerrar sesión",
    // Registration page
    createAccount: "Cree su cuenta de Sekcion",
    personalizeExperience: "Conozcámoslo mejor para personalizar su experiencia",
    firstName: "Nombre",
    lastName: "Apellido",
    usernamePreview: "Vista previa del nombre de usuario",
    profileAppear: "Así es como aparecerá su perfil",
    skipToDashboard: "Saltar al panel"
  },
  french: {
    welcomeTitle: "Bienvenue sur Sekcion",
    welcomeSubtitle: "Sekcion est l'espace de travail de contenu pour partager des publications précieuses tous les jours.",
    welcomeDescription: "Recevez des publications Twitter personnalisées et optimisées par algorithme en <5 minutes.",
    getStarted: "Commencer",
    back: "Retour",
    continue: "Continuer",
    choosePlan: "Comment souhaitez-vous utiliser Sekcion ?",
    setupWorkspace: "Nous configurerons votre espace de travail en conséquence.",
    forTeam: "Pour mon équipe",
    forPersonal: "Pour usage personnel",
    teamDescription: "Un endroit pour créer, examiner et suivre le contenu pour votre équipe.",
    personalDescription: "Créez du contenu pour un seul profil Twitter.",
    chooseStyle: "Choisissez votre style",
    styleDescription: "Vous pouvez modifier le style de l'interface à tout moment dans les paramètres.",
    light: "Clair",
    dark: "Sombre",
    chooseLanguage: "Choisissez la langue de votre contenu",
    languageDescription: "Sekcion est en anglais, mais vous pouvez répondre à toutes les questions dans la langue de votre choix à tout moment.",
    english: "Anglais",
    german: "Allemand",
    spanish: "Espagnol",
    french: "Français",
    englishDescription: "Recommandé pour la plupart des utilisateurs pour atteindre un public plus large.",
    germanDescription: "Recommandé si votre public principal est allemand.",
    spanishDescription: "Recommandé si votre public principal est hispanophone.",
    frenchDescription: "Recommandé si votre public principal est francophone.",
    formatTitle: "Choisissez votre style de formatage de publication préféré",
    formatDescription: "Sekcion est formé sur des millions de publications virales. Lorsque vous créez des publications, les meilleures publications sur les mêmes sujets seront utilisées comme référence.",
    postLength: "Longueur de la publication",
    superLong: "Super longue",
    learnPreferences: "Sekcion apprendra vos préférences individuelles au fil du temps.",
    frequencyTitle: "Combien de fois souhaitez-vous publier par semaine ?",
    frequencyDescription: "Nous recommandons de publier au moins 1 à 2 fois par semaine.",
    postingSchedule: "Calendrier de publication",
    optimalTime: "Heure optimale de publication",
    aiSuggest: "L'IA suggérera",
    onePostWeek: "Une publication par semaine",
    postsPerWeek: "publications par semaine",
    teamInviteTitle: "Inviter des membres à",
    teamInviteDescription: "Les membres de l'équipe peuvent collaborer à la création de contenu et partager des analyses.",
    addTeamMembers: "Inviter des membres de l'équipe",
    placeholderEmail: "collegue@exemple.com",
    add: "Ajouter",
    teamMembers: "Membres de l'équipe",
    noMembers: "Aucun membre d'équipe ajouté pour le moment",
    admin: "Administrateur",
    member: "Membre",
    canInviteLater: "Vous pouvez inviter plus de membres après la configuration",
    // Dashboard translations
    create: "Créer",
    schedule: "Programmer",
    analytics: "Analytique",
    myTweets: "Mes Tweets",
    createNewTweet: "Créer un nouveau Tweet",
    recordVoice: "Enregistrer la voix",
    uploadMedia: "Télécharger des médias",
    writeText: "Écrire du texte",
    whatsHappening: "Que se passe-t-il ?",
    characters: "caractères",
    generateWithAI: "Générer avec l'IA",
    postTweet: "Publier le Tweet",
    preview: "Aperçu",
    previewDescription: "Voyez comment votre tweet apparaîtra",
    upcomingTweets: "Tweets à venir",
    scheduledPublication: "Programmés pour publication",
    viewCalendar: "Voir le calendrier",
    aiSuggestions: "Suggestions de l'IA",
    trendingTopics: "Sujets tendance à écrire",
    contentCalendar: "Calendrier de contenu",
    manageSchedule: "Gérez et programmez vos prochains tweets",
    impressions: "Impressions",
    totalViews: "Vues totales de vos tweets",
    engagementRate: "Taux d'engagement",
    interactions: "Interactions avec votre contenu",
    followersGrowth: "Croissance des abonnés",
    newFollowers: "Nouveaux abonnés au fil du temps",
    profile: "Profil",
    settings: "Paramètres",
    connectTwitter: "Connecter Twitter",
    logout: "Déconnexion",
    // Registration page
    createAccount: "Créez votre compte Sekcion",
    personalizeExperience: "Apprenons à mieux vous connaître pour personnaliser votre expérience",
    firstName: "Prénom",
    lastName: "Nom",
    usernamePreview: "Aperçu du nom d'utilisateur",
    profileAppear: "Voici comment votre profil apparaîtra",
    skipToDashboard: "Aller au tableau de bord"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    // Check if language is saved in localStorage
    const savedLanguage = localStorage.getItem("language") as Language;
    
    // Default to English if no saved preference
    return savedLanguage || "english";
  });

  useEffect(() => {
    // Save to localStorage
    localStorage.setItem("language", language);
    
    // Set language attribute on html tag
    document.documentElement.setAttribute("lang", 
      language === "english" ? "en" : 
      language === "german" ? "de" : 
      language === "spanish" ? "es" : 
      language === "french" ? "fr" : "en"
    );
  }, [language]);

  // Translation function
  const t = (key: string): string => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
} 