import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "english" | "german" | "spanish" | "french" | "italian" | "portuguese" | "russian";

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

// Simple translation dictionary
const translations: Record<Language, Record<string, string>> = {
  english: {
    welcomeTitle: "Welcome to Scripe",
    welcomeSubtitle: "Scripe is the content workspace to share valuable posts everyday.",
    welcomeDescription: "Receive tailored, algorithm-optimized Twitter posts in <5 minutes.",
    getStarted: "Get started",
    back: "Back",
    continue: "Continue",
    choosePlan: "How would you like to use Scripe?",
    setupWorkspace: "We'll setup your workspace accordingly.",
    forTeam: "For my team",
    forPersonal: "For personal use",
    teamDescription: "One place to create, review and track content for your team.",
    personalDescription: "Create content for a single Twitter profile.",
    chooseStyle: "Choose your style",
    styleDescription: "You can change the UI style at any time in the settings.",
    light: "Light",
    dark: "Dark",
    chooseLanguage: "Choose the language of your content",
    languageDescription: "Scripe is in English but you can answer all questions in your chosen language at all times.",
    english: "English",
    german: "German",
    spanish: "Spanish",
    french: "French",
    italian: "Italian",
    portuguese: "Portuguese", 
    russian: "Russian",
    englishDescription: "Recommended for most users to reach larger audience.",
    germanDescription: "Recommended if your main audience is German.",
    spanishDescription: "Recommended if your main audience is Spanish-speaking.",
    frenchDescription: "Recommended if your main audience is French-speaking.",
    italianDescription: "Recommended if your main audience is Italian-speaking.",
    portugueseDescription: "Recommended if your main audience is Portuguese-speaking.",
    russianDescription: "Recommended if your main audience is Russian-speaking.",
    formatTitle: "Pick your preferred post formatting style",
    formatDescription: "Scripe is trained on millions of viral posts. When you create posts, the best performing posts about the same topics will be used as a reference.",
    postLength: "Post length",
    superLong: "Super long",
    learnPreferences: "Scripe will learn your individual preferences over time.",
    frequencyTitle: "How often do you want to post per week?",
    frequencyDescription: "We recommend posting at least 1-2 times per week.",
    postingSchedule: "Posting Schedule",
    optimalTime: "Optimal posting time",
    aiSuggest: "AI will suggest",
    onePostWeek: "One post per week",
    postsPerWeek: "posts per week",
    teamInviteTitle: "Invite members to",
    teamInviteDescription: "Team members can collaborate on content creation and share analytics.",
    addTeamMembers: "Invite team members",
    placeholderEmail: "colleague@example.com",
    add: "Add",
    teamMembers: "Team members",
    noMembers: "No team members added yet",
    admin: "Admin",
    member: "Member",
    canInviteLater: "You can invite more members after setup is complete"
  },
  german: {
    welcomeTitle: "Willkommen bei Scripe",
    welcomeSubtitle: "Scripe ist der Content-Workspace, um täglich wertvolle Beiträge zu teilen.",
    welcomeDescription: "Erhalten Sie maßgeschneiderte, algorithmusoptimierte Twitter-Beiträge in <5 Minuten.",
    getStarted: "Loslegen",
    back: "Zurück",
    continue: "Weiter",
    choosePlan: "Wie möchten Sie Scripe nutzen?",
    setupWorkspace: "Wir richten Ihren Arbeitsbereich entsprechend ein.",
    forTeam: "Für mein Team",
    forPersonal: "Für persönliche Nutzung",
    teamDescription: "Ein Ort zum Erstellen, Überprüfen und Verfolgen von Inhalten für Ihr Team.",
    personalDescription: "Erstellen Sie Inhalte für ein einzelnes Twitter-Profil.",
    chooseStyle: "Wählen Sie Ihren Stil",
    styleDescription: "Sie können den UI-Stil jederzeit in den Einstellungen ändern.",
    light: "Hell",
    dark: "Dunkel",
    chooseLanguage: "Wählen Sie die Sprache Ihrer Inhalte",
    languageDescription: "Scripe ist auf Englisch, aber Sie können alle Fragen jederzeit in Ihrer gewählten Sprache beantworten.",
    english: "Englisch",
    german: "Deutsch",
    spanish: "Spanisch",
    french: "Französisch",
    italian: "Italienisch",
    portuguese: "Portugiesisch",
    russian: "Russisch",
    englishDescription: "Empfohlen für die meisten Benutzer, um ein größeres Publikum zu erreichen.",
    germanDescription: "Empfohlen, wenn Ihre Hauptzielgruppe deutsch ist.",
    spanishDescription: "Empfohlen, wenn Ihre Hauptzielgruppe spanisch ist.",
    frenchDescription: "Empfohlen, wenn Ihre Hauptzielgruppe französisch ist.",
    italianDescription: "Empfohlen, wenn Ihre Hauptzielgruppe italienisch ist.",
    portugueseDescription: "Empfohlen, wenn Ihre Hauptzielgruppe portugiesisch ist.",
    russianDescription: "Empfohlen, wenn Ihre Hauptzielgruppe russisch ist.",
    formatTitle: "Wählen Sie Ihren bevorzugten Beitragsformatierungsstil",
    formatDescription: "Scripe wird mit Millionen viraler Beiträge trainiert. Wenn Sie Beiträge erstellen, werden die besten Beiträge zu ähnlichen Themen als Referenz verwendet.",
    postLength: "Beitragslänge",
    superLong: "Sehr lang",
    learnPreferences: "Scripe lernt mit der Zeit Ihre individuellen Präferenzen.",
    frequencyTitle: "Wie oft möchten Sie pro Woche posten?",
    frequencyDescription: "Wir empfehlen, mindestens 1-2 Mal pro Woche zu posten.",
    postingSchedule: "Posting-Zeitplan",
    optimalTime: "Optimale Posting-Zeit",
    aiSuggest: "KI wird vorschlagen",
    onePostWeek: "Ein Beitrag pro Woche",
    postsPerWeek: "Beiträge pro Woche",
    teamInviteTitle: "Laden Sie Mitglieder ein zu",
    teamInviteDescription: "Teammitglieder können bei der Erstellung von Inhalten zusammenarbeiten und Analysen teilen.",
    addTeamMembers: "Teammitglieder einladen",
    placeholderEmail: "kollege@beispiel.de",
    add: "Hinzufügen",
    teamMembers: "Teammitglieder",
    noMembers: "Noch keine Teammitglieder hinzugefügt",
    admin: "Administrator",
    member: "Mitglied",
    canInviteLater: "Sie können nach Abschluss der Einrichtung weitere Mitglieder einladen"
  },
  spanish: {
    welcomeTitle: "Bienvenido a Scripe",
    welcomeSubtitle: "Scripe es el espacio de trabajo de contenido para compartir publicaciones valiosas todos los días.",
    welcomeDescription: "Reciba publicaciones de Twitter optimizadas por algoritmos y personalizadas en <5 minutos.",
    getStarted: "Comenzar",
    back: "Atrás",
    continue: "Continuar",
    choosePlan: "¿Cómo le gustaría usar Scripe?",
    setupWorkspace: "Configuraremos su espacio de trabajo en consecuencia.",
    forTeam: "Para mi equipo",
    forPersonal: "Para uso personal",
    teamDescription: "Un lugar para crear, revisar y seguir el contenido de su equipo.",
    personalDescription: "Cree contenido para un solo perfil de Twitter.",
    chooseStyle: "Elija su estilo",
    styleDescription: "Puede cambiar el estilo de la interfaz en cualquier momento en la configuración.",
    light: "Claro",
    dark: "Oscuro",
    chooseLanguage: "Elija el idioma de su contenido",
    languageDescription: "Scripe está en inglés, pero puede responder todas las preguntas en su idioma elegido en todo momento.",
    english: "Inglés",
    german: "Alemán",
    spanish: "Español",
    french: "Francés",
    italian: "Italiano",
    portuguese: "Portugués",
    russian: "Ruso",
    englishDescription: "Recomendado para la mayoría de los usuarios para llegar a una audiencia más amplia.",
    germanDescription: "Recomendado si su audiencia principal es alemana.",
    spanishDescription: "Recomendado si su audiencia principal habla español.",
    frenchDescription: "Recomendado si su audiencia principal habla francés.",
    italianDescription: "Recomendado si su audiencia principal habla italiano.",
    portugueseDescription: "Recomendado si su audiencia principal habla portugués.",
    russianDescription: "Recomendado si su audiencia principal habla ruso.",
    formatTitle: "Elija su estilo de formato de publicación preferido",
    formatDescription: "Scripe está entrenado en millones de publicaciones virales. Cuando cree publicaciones, las mejores publicaciones sobre los mismos temas se utilizarán como referencia.",
    postLength: "Longitud de la publicación",
    superLong: "Súper largo",
    learnPreferences: "Scripe aprenderá sus preferencias individuales con el tiempo.",
    frequencyTitle: "¿Con qué frecuencia desea publicar por semana?",
    frequencyDescription: "Recomendamos publicar al menos 1-2 veces por semana.",
    postingSchedule: "Calendario de publicación",
    optimalTime: "Tiempo óptimo de publicación",
    aiSuggest: "La IA sugerirá",
    onePostWeek: "Una publicación por semana",
    postsPerWeek: "publicaciones por semana",
    teamInviteTitle: "Invitar miembros a",
    teamInviteDescription: "Los miembros del equipo pueden colaborar en la creación de contenido y compartir análisis.",
    addTeamMembers: "Invitar miembros del equipo",
    placeholderEmail: "colega@ejemplo.com",
    add: "Añadir",
    teamMembers: "Miembros del equipo",
    noMembers: "Aún no se han añadido miembros al equipo",
    admin: "Administrador",
    member: "Miembro",
    canInviteLater: "Puede invitar a más miembros después de completar la configuración"
  },
  french: {
    welcomeTitle: "Bienvenue sur Scripe",
    welcomeSubtitle: "Scripe est l'espace de travail de contenu pour partager des publications précieuses tous les jours.",
    welcomeDescription: "Recevez des publications Twitter personnalisées et optimisées par algorithme en <5 minutes.",
    getStarted: "Commencer",
    back: "Retour",
    continue: "Continuer",
    choosePlan: "Comment souhaitez-vous utiliser Scripe ?",
    setupWorkspace: "Nous configurerons votre espace de travail en conséquence.",
    forTeam: "Pour mon équipe",
    forPersonal: "Pour un usage personnel",
    teamDescription: "Un lieu pour créer, examiner et suivre le contenu de votre équipe.",
    personalDescription: "Créez du contenu pour un seul profil Twitter.",
    chooseStyle: "Choisissez votre style",
    styleDescription: "Vous pouvez modifier le style de l'interface à tout moment dans les paramètres.",
    light: "Clair",
    dark: "Sombre",
    chooseLanguage: "Choisissez la langue de votre contenu",
    languageDescription: "Scripe est en anglais, mais vous pouvez répondre à toutes les questions dans la langue de votre choix à tout moment.",
    english: "Anglais",
    german: "Allemand",
    spanish: "Espagnol",
    french: "Français",
    italian: "Italien",
    portuguese: "Portugais",
    russian: "Russe",
    englishDescription: "Recommandé pour la plupart des utilisateurs pour atteindre un public plus large.",
    germanDescription: "Recommandé si votre public principal est allemand.",
    spanishDescription: "Recommandé si votre public principal est hispanophone.",
    frenchDescription: "Recommandé si votre public principal est francophone.",
    italianDescription: "Recommandé si votre public principal est italophone.",
    portugueseDescription: "Recommandé si votre public principal est lusophone.",
    russianDescription: "Recommandé si votre public principal est russophone.",
    formatTitle: "Choisissez votre style de formatage de publication préféré",
    formatDescription: "Scripe est formé sur des millions de publications virales. Lorsque vous créez des publications, les meilleures publications sur les mêmes sujets seront utilisées comme référence.",
    postLength: "Longueur de la publication",
    superLong: "Super long",
    learnPreferences: "Scripe apprendra vos préférences individuelles au fil du temps.",
    frequencyTitle: "À quelle fréquence souhaitez-vous publier par semaine ?",
    frequencyDescription: "Nous recommandons de publier au moins 1 à 2 fois par semaine.",
    postingSchedule: "Calendrier de publication",
    optimalTime: "Heure de publication optimale",
    aiSuggest: "L'IA suggérera",
    onePostWeek: "Une publication par semaine",
    postsPerWeek: "publications par semaine",
    teamInviteTitle: "Inviter des membres à",
    teamInviteDescription: "Les membres de l'équipe peuvent collaborer à la création de contenu et partager des analyses.",
    addTeamMembers: "Inviter des membres de l'équipe",
    placeholderEmail: "collegue@exemple.fr",
    add: "Ajouter",
    teamMembers: "Membres de l'équipe",
    noMembers: "Aucun membre de l'équipe ajouté pour l'instant",
    admin: "Administrateur",
    member: "Membre",
    canInviteLater: "Vous pourrez inviter d'autres membres après la configuration"
  },
  italian: {
    welcomeTitle: "Benvenuto su Scripe",
    welcomeSubtitle: "Scripe è lo spazio di lavoro per i contenuti per condividere post preziosi ogni giorno.",
    welcomeDescription: "Ricevi post Twitter ottimizzati e personalizzati in <5 minuti.",
    getStarted: "Inizia",
    back: "Indietro",
    continue: "Continua",
    choosePlan: "Come desideri utilizzare Scripe?",
    setupWorkspace: "Configureremo il tuo spazio di lavoro di conseguenza.",
    forTeam: "Per il mio team",
    forPersonal: "Per uso personale",
    teamDescription: "Un luogo per creare, rivedere e monitorare i contenuti per il tuo team.",
    personalDescription: "Crea contenuti per un singolo profilo Twitter.",
    chooseStyle: "Scegli il tuo stile",
    styleDescription: "Puoi cambiare lo stile dell'interfaccia in qualsiasi momento nelle impostazioni.",
    light: "Chiaro",
    dark: "Scuro",
    chooseLanguage: "Scegli la lingua dei tuoi contenuti",
    languageDescription: "Scripe è in inglese, ma puoi rispondere a tutte le domande nella lingua scelta in qualsiasi momento.",
    english: "Inglese",
    german: "Tedesco",
    spanish: "Spagnolo",
    french: "Francese",
    italian: "Italiano",
    portuguese: "Portoghese",
    russian: "Russo",
    englishDescription: "Consigliato per la maggior parte degli utenti per raggiungere un pubblico più ampio.",
    germanDescription: "Consigliato se il tuo pubblico principale è tedesco.",
    spanishDescription: "Consigliato se il tuo pubblico principale è di lingua spagnola.",
    frenchDescription: "Consigliato se il tuo pubblico principale è di lingua francese.",
    italianDescription: "Consigliato se il tuo pubblico principale è di lingua italiana.",
    portugueseDescription: "Consigliato se il tuo pubblico principale è di lingua portoghese.",
    russianDescription: "Consigliato se il tuo pubblico principale è di lingua russa.",
    formatTitle: "Scegli il tuo stile di formattazione del post preferito",
    formatDescription: "Scripe è addestrato su milioni di post virali. Quando crei post, i migliori post sugli stessi argomenti saranno usati come riferimento.",
    postLength: "Lunghezza del post",
    superLong: "Super lungo",
    learnPreferences: "Scripe imparerà le tue preferenze individuali nel tempo.",
    frequencyTitle: "Quanto spesso vuoi pubblicare a settimana?",
    frequencyDescription: "Consigliamo di pubblicare almeno 1-2 volte a settimana.",
    postingSchedule: "Programma di pubblicazione",
    optimalTime: "Orario ottimale di pubblicazione",
    aiSuggest: "L'IA suggerirà",
    onePostWeek: "Un post a settimana",
    postsPerWeek: "post a settimana",
    teamInviteTitle: "Invita membri a",
    teamInviteDescription: "I membri del team possono collaborare alla creazione di contenuti e condividere analisi.",
    addTeamMembers: "Invita membri del team",
    placeholderEmail: "collega@esempio.it",
    add: "Aggiungi",
    teamMembers: "Membri del team",
    noMembers: "Nessun membro del team aggiunto finora",
    admin: "Amministratore",
    member: "Membro",
    canInviteLater: "Puoi invitare altri membri dopo aver completato la configurazione"
  },
  portuguese: {
    welcomeTitle: "Bem-vindo ao Scripe",
    welcomeSubtitle: "O Scripe é o espaço de trabalho de conteúdo para compartilhar postagens valiosas todos os dias.",
    welcomeDescription: "Receba postagens do Twitter personalizadas e otimizadas por algoritmo em <5 minutos.",
    getStarted: "Começar",
    back: "Voltar",
    continue: "Continuar",
    choosePlan: "Como você gostaria de usar o Scripe?",
    setupWorkspace: "Configuraremos seu espaço de trabalho de acordo.",
    forTeam: "Para minha equipe",
    forPersonal: "Para uso pessoal",
    teamDescription: "Um lugar para criar, revisar e acompanhar o conteúdo da sua equipe.",
    personalDescription: "Crie conteúdo para um único perfil do Twitter.",
    chooseStyle: "Escolha seu estilo",
    styleDescription: "Você pode alterar o estilo da interface a qualquer momento nas configurações.",
    light: "Claro",
    dark: "Escuro",
    chooseLanguage: "Escolha o idioma do seu conteúdo",
    languageDescription: "O Scripe está em inglês, mas você pode responder a todas as perguntas no idioma escolhido a qualquer momento.",
    english: "Inglês",
    german: "Alemão",
    spanish: "Espanhol",
    french: "Francês",
    italian: "Italiano",
    portuguese: "Português",
    russian: "Russo",
    englishDescription: "Recomendado para a maioria dos usuários para alcançar um público maior.",
    germanDescription: "Recomendado se seu público principal for alemão.",
    spanishDescription: "Recomendado se seu público principal for de língua espanhola.",
    frenchDescription: "Recomendado se seu público principal for de língua francesa.",
    italianDescription: "Recomendado se seu público principal for de língua italiana.",
    portugueseDescription: "Recomendado se seu público principal for de língua portuguesa.",
    russianDescription: "Recomendado se seu público principal for de língua russa.",
    formatTitle: "Escolha seu estilo de formatação de postagem preferido",
    formatDescription: "O Scripe é treinado em milhões de postagens virais. Quando você cria postagens, as melhores postagens sobre os mesmos tópicos serão usadas como referência.",
    postLength: "Comprimento da postagem",
    superLong: "Super longo",
    learnPreferences: "O Scripe aprenderá suas preferências individuais ao longo do tempo.",
    frequencyTitle: "Com que frequência você deseja postar por semana?",
    frequencyDescription: "Recomendamos postar pelo menos 1-2 vezes por semana.",
    postingSchedule: "Cronograma de postagem",
    optimalTime: "Tempo ideal de postagem",
    aiSuggest: "A IA irá sugerir",
    onePostWeek: "Uma postagem por semana",
    postsPerWeek: "postagens por semana",
    teamInviteTitle: "Convidar membros para",
    teamInviteDescription: "Os membros da equipe podem colaborar na criação de conteúdo e compartilhar análises.",
    addTeamMembers: "Convidar membros da equipe",
    placeholderEmail: "colega@exemplo.com",
    add: "Adicionar",
    teamMembers: "Membros da equipe",
    noMembers: "Ainda não há membros da equipe adicionados",
    admin: "Administrador",
    member: "Membro",
    canInviteLater: "Você pode convidar mais membros após a conclusão da configuração"
  },
  russian: {
    welcomeTitle: "Добро пожаловать в Scripe",
    welcomeSubtitle: "Scripe — это рабочее пространство для ежедневного обмена ценными публикациями.",
    welcomeDescription: "Получайте индивидуальные, оптимизированные алгоритмом публикации Twitter за <5 минут.",
    getStarted: "Начать",
    back: "Назад",
    continue: "Продолжить",
    choosePlan: "Как бы вы хотели использовать Scripe?",
    setupWorkspace: "Мы настроим ваше рабочее пространство соответствующим образом.",
    forTeam: "Для моей команды",
    forPersonal: "Для личного использования",
    teamDescription: "Одно место для создания, просмотра и отслеживания контента для вашей команды.",
    personalDescription: "Создавайте контент для одного профиля Twitter.",
    chooseStyle: "Выберите свой стиль",
    styleDescription: "Вы можете изменить стиль интерфейса в любое время в настройках.",
    light: "Светлый",
    dark: "Темный",
    chooseLanguage: "Выберите язык вашего контента",
    languageDescription: "Scripe на английском языке, но вы можете отвечать на все вопросы на выбранном вами языке в любое время.",
    english: "Английский",
    german: "Немецкий",
    spanish: "Испанский",
    french: "Французский",
    italian: "Итальянский",
    portuguese: "Португальский",
    russian: "Русский",
    englishDescription: "Рекомендуется для большинства пользователей для охвата более широкой аудитории.",
    germanDescription: "Рекомендуется, если ваша основная аудитория говорит на немецком языке.",
    spanishDescription: "Рекомендуется, если ваша основная аудитория говорит на испанском языке.",
    frenchDescription: "Рекомендуется, если ваша основная аудитория говорит на французском языке.",
    italianDescription: "Рекомендуется, если ваша основная аудитория говорит на итальянском языке.",
    portugueseDescription: "Рекомендуется, если ваша основная аудитория говорит на португальском языке.",
    russianDescription: "Рекомендуется, если ваша основная аудитория говорит на русском языке.",
    formatTitle: "Выберите предпочтительный стиль форматирования публикаций",
    formatDescription: "Scripe обучен на миллионах вирусных публикаций. Когда вы создаете публикации, лучшие публикации по тем же темам будут использоваться в качестве ориентира.",
    postLength: "Длина публикации",
    superLong: "Очень длинный",
    learnPreferences: "Scripe со временем изучит ваши индивидуальные предпочтения.",
    frequencyTitle: "Как часто вы хотите публиковать в неделю?",
    frequencyDescription: "Мы рекомендуем публиковать не менее 1-2 раз в неделю.",
    postingSchedule: "Расписание публикаций",
    optimalTime: "Оптимальное время публикации",
    aiSuggest: "ИИ предложит",
    onePostWeek: "Одна публикация в неделю",
    postsPerWeek: "публикаций в неделю",
    teamInviteTitle: "Пригласить участников в",
    teamInviteDescription: "Члены команды могут сотрудничать в создании контента и делиться аналитикой.",
    addTeamMembers: "Пригласить членов команды",
    placeholderEmail: "коллега@пример.рф",
    add: "Добавить",
    teamMembers: "Члены команды",
    noMembers: "Пока не добавлено ни одного члена команды",
    admin: "Администратор",
    member: "Участник",
    canInviteLater: "Вы можете пригласить больше участников после завершения настройки"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    // Check if language is saved in localStorage
    const savedLanguage = localStorage.getItem("language") as Language;
    
    // Default to English if no saved preference
    return savedLanguage || "english";
  });

  useEffect(() => {
    // Save to localStorage
    localStorage.setItem("language", language);
    
    // Set language attribute on html tag
    const langCode = {
      english: "en",
      german: "de",
      spanish: "es",
      french: "fr",
      italian: "it",
      portuguese: "pt",
      russian: "ru"
    }[language];
    
    document.documentElement.setAttribute("lang", langCode);
  }, [language]);

  // Translation function
  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
} 